"use client";

/**
 * Activity Feed Component
 * Displays unified timeline of automation events (detections, price changes, alerts)
 */

import { useQuery } from "convex/react";
import { api } from "../../../../convex/_generated/api";
import { useUser } from "@clerk/nextjs";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Sparkles, TrendingUp, AlertCircle, CheckCircle2, XCircle, Bell, ArrowUpRight } from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import { Skeleton } from "@/components/ui/skeleton";

interface DetectionData {
  proposedName: string;
  proposedAmount: number;
  proposedCadence: string;
  confidence: number;
}

interface PriceChangeData {
  subscriptionName: string;
  subscriptionId?: string;
  oldPrice: number;
  newPrice: number;
  percentChange: number;
}

interface NotificationData {
  title: string;
  message: string;
}

interface ActivityItem {
  id: string;
  type: "detection_accepted" | "detection_dismissed" | "price_change" | "notification";
  timestamp: number;
  data: DetectionData | PriceChangeData | NotificationData;
}

export function ActivityFeed() {
  const { user } = useUser();
  const feed = useQuery(
    api.insights.getActivityFeed,
    user?.id ? { clerkUserId: user.id, limit: 50 } : "skip"
  );

  if (feed === undefined) {
    return (
      <Card>
        <CardHeader>
          <Skeleton className="h-5 w-40" />
          <Skeleton className="h-4 w-64" />
        </CardHeader>
        <CardContent className="space-y-4">
          {[...Array(4)].map((_, i) => (
            <Skeleton key={i} className="h-20 w-full" />
          ))}
        </CardContent>
      </Card>
    );
  }

  if (feed.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle className="font-sans text-base">Automation Activity</CardTitle>
          <CardDescription className="font-sans">
            When SubWise detects subscriptions, price changes, or sends alerts, you&apos;ll see the
            history here.
          </CardDescription>
        </CardHeader>
        <CardContent className="flex flex-col items-center justify-center py-8">
          <div className="rounded-full bg-muted p-6 mb-4">
            <Sparkles className="h-10 w-10 text-muted-foreground" />
          </div>
          <h3 className="font-semibold text-lg mb-2 font-sans">No automation activity yet</h3>
          <p className="text-sm text-muted-foreground text-center max-w-md font-sans">
            Connect Gmail and start accepting detections to see how SubWise has been working for
            you over time.
          </p>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle className="font-sans text-base">Automation Activity</CardTitle>
        <CardDescription className="font-sans">
          Most recent detections, price changes, and alerts generated by SubWise.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-3">
        <p className="text-xs text-muted-foreground font-sans">
          Showing {feed.length} recent {feed.length === 1 ? "event" : "events"}
        </p>
        {feed.map((item: ActivityItem) => (
          <ActivityFeedItem key={item.id} item={item} />
        ))}
      </CardContent>
    </Card>
  );
}

function ActivityFeedItem({ item }: { item: ActivityItem }) {
  const getIcon = () => {
    switch (item.type) {
      case "detection_accepted":
        return <CheckCircle2 className="h-5 w-5 text-green-600" />;
      case "detection_dismissed":
        return <XCircle className="h-5 w-5 text-muted-foreground" />;
      case "price_change":
        return <TrendingUp className="h-5 w-5 text-orange-600" />;
      case "notification":
        return <Bell className="h-5 w-5 text-blue-600" />;
      default:
        return <AlertCircle className="h-5 w-5 text-muted-foreground" />;
    }
  };

  const getBadgeVariant = () => {
    switch (item.type) {
      case "detection_accepted":
        return "default";
      case "detection_dismissed":
        return "secondary";
      case "price_change":
        return "destructive";
      case "notification":
        return "outline";
      default:
        return "secondary";
    }
  };

  const getBadgeText = () => {
    switch (item.type) {
      case "detection_accepted":
        return "Accepted";
      case "detection_dismissed":
        return "Dismissed";
      case "price_change":
        return "Price Change";
      case "notification":
        return "Alert";
      default:
        return "Activity";
    }
  };

  const getTitle = () => {
    switch (item.type) {
      case "detection_accepted":
        return `Detected: ${(item.data as DetectionData).proposedName}`;
      case "detection_dismissed":
        return `Dismissed detection: ${(item.data as DetectionData).proposedName}`;
      case "price_change":
        return `Price change: ${(item.data as PriceChangeData).subscriptionName}`;
      case "notification":
        return (item.data as NotificationData).title;
      default:
        return "Activity";
    }
  };

  const getDescription = () => {
    switch (item.type) {
      case "detection_accepted": {
        const data = item.data as DetectionData;
        return (
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-semibold text-foreground">
              ${data.proposedAmount.toFixed(2)}
            </span>
            <span className="text-muted-foreground">/{data.proposedCadence}</span>
            <Badge variant="outline" className="text-xs">
              {Math.round(data.confidence * 100)}% confidence
            </Badge>
          </div>
        );
      }
      case "detection_dismissed": {
        const data = item.data as DetectionData;
        return (
          <span className="text-muted-foreground">
            ${data.proposedAmount.toFixed(2)}/{data.proposedCadence}
          </span>
        );
      }
      case "price_change": {
        const data = item.data as PriceChangeData;
        const change = data.percentChange > 0 ? "+" : "";
        const color = data.percentChange > 0 ? "text-red-600" : "text-green-600";
        return (
          <div className="flex items-center gap-2 flex-wrap">
            <span className="text-muted-foreground">
              ${data.oldPrice.toFixed(2)} → ${data.newPrice.toFixed(2)}
            </span>
            <span className={`font-medium ${color}`}>
              ({change}{data.percentChange.toFixed(1)}%)
            </span>
            {data.subscriptionId && (
              <a
                href={`/dashboard/subscriptions?sub=${data.subscriptionId}`}
                className="inline-flex items-center text-xs text-primary hover:underline font-sans"
              >
                View subscription
                <ArrowUpRight className="h-3 w-3 ml-1" />
              </a>
            )}
          </div>
        );
      }
      case "notification":
        return <span className="text-muted-foreground">{(item.data as NotificationData).message}</span>;
      default:
        return null;
    }
  };

  return (
    <Card className="hover:border-primary/50 transition-colors">
      <CardContent className="flex items-start gap-4 p-4">
        {/* Icon */}
        <div className="rounded-full bg-muted p-2.5 flex-shrink-0 mt-0.5">
          {getIcon()}
        </div>

        {/* Content */}
        <div className="flex-1 min-w-0 space-y-2">
          {/* Title and Time */}
          <div className="flex items-start justify-between gap-2">
            <h4 className="font-medium font-sans leading-tight">{getTitle()}</h4>
            <div className="flex items-center gap-2 flex-shrink-0">
              <Badge variant={getBadgeVariant()} className="text-xs font-sans">
                {getBadgeText()}
              </Badge>
            </div>
          </div>

          {/* Description */}
          <div className="text-sm font-sans">{getDescription()}</div>

          {/* Timestamp */}
          <div className="text-xs text-muted-foreground font-sans">
            {formatDistanceToNow(item.timestamp, { addSuffix: true })}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
